# Generated by Django 5.2.4 on 2025-11-17 06:05

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0002_initial'),
        ('license_template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('document'), models.Model),
        ),
        migrations.CreateModel(
            name='ApplicationDocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_templates', to='application.application', verbose_name='Заявка')),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_templates', to='license_template.licensetemplatefield', verbose_name='Поле')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_templates', to='license_template.licensetemplate', verbose_name='Шаблон')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_templates', to='document.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('application-document-template'), models.Model),
        ),
        migrations.CreateModel(
            name='DocumentExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='document-examples/', verbose_name='Пример документа')),
                ('field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_examples', to='license_template.licensetemplatefield', verbose_name='Поле к которому нужно прикрепить пример документа')),
            ],
            options={
                'verbose_name': 'Пример документа',
                'verbose_name_plural': 'Примеры документов',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('document-example'), models.Model),
        ),
    ]
