# Generated by Django 5.2.4 on 2025-11-17 06:05

import apps.account.manager
import django.db.models.deletion
import django.utils.timezone
import django_prometheus.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Директор'), (1, 'Начальник управления'), (2, 'Специалист'), (3, 'Общий отдел')], null=True, verbose_name='Роль сотрудника')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус сотрудника')),
                ('tin', models.CharField(blank=True, max_length=15, null=True, verbose_name='ИНН')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('users'), models.Model),
            managers=[
                ('objects', apps.account.manager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserResetPasswordToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Токен для сброса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Токен для восстановления пароля',
                'verbose_name_plural': 'Токены для восстановления пароля',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('reset tokens'), models.Model),
        ),
    ]
