# Generated by Django 5.2.4 on 2025-11-17 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер')),
                ('date_of_issue', models.DateField(verbose_name='Дата выдачи')),
                ('scan', models.FileField(upload_to='decree_scan', verbose_name='Скан')),
                ('scan_ru', models.FileField(null=True, upload_to='decree_scan', verbose_name='Скан')),
                ('scan_ky', models.FileField(null=True, upload_to='decree_scan', verbose_name='Скан')),
                ('aplication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decree', to='application.application', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Приказ',
                'verbose_name_plural': 'Приказы',
            },
        ),
    ]
