# Generated by Django 5.2.4 on 2025-11-17 06:05

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django_prometheus.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Принятая на рассмотрение заявка',
                'verbose_name_plural': 'Принятые на рассмотрение заявки',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('application-employees'), models.Model),
        ),
        migrations.CreateModel(
            name='ApprovedRejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=None, null=True, verbose_name='Подтверждение')),
                ('rejected', models.BooleanField(default=None, null=True, verbose_name='Отказ')),
                ('reason_for_refusal', models.TextField(blank=True, null=True, verbose_name='Причина отказа')),
            ],
            options={
                'verbose_name': 'Подтверждение и отказ',
                'verbose_name_plural': 'Подтверждения и отказы',
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='receipt/', verbose_name='Чек об оплате')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Отправлено'), (1, 'Не отправлено'), (2, 'В ожидании')], null=True, verbose_name='Статус отправки')),
                ('organization_name', models.CharField(max_length=100, verbose_name='Название организации')),
                ('applicants_status', models.PositiveSmallIntegerField(choices=[(0, 'Физ. лицо'), (1, 'Юр. лицо')], verbose_name='Статус заявителя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^996\\d{9}$', message='Номер телефона должен быть заполнен в формате: 996*********** Разрешено до 9 символов после кода страны.')], verbose_name='Номер телефона')),
                ('other_information', models.TextField(blank=True, null=True, verbose_name='Другие сведения')),
                ('applicants_full_name', models.CharField(max_length=300, verbose_name='ФИО заявителя')),
                ('form_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='Организационно правовая форма')),
                ('ownership_form', models.CharField(max_length=30, verbose_name='Форма собственности')),
                ('legal_address', models.CharField(max_length=500, verbose_name='Юридический адрес')),
                ('actual_address', models.CharField(max_length=500, verbose_name='Фактический адрес')),
                ('inn', models.CharField(validators=[django.core.validators.MinLengthValidator(14), django.core.validators.MaxLengthValidator(14)], verbose_name='ИНН')),
                ('okpo_code', models.CharField(max_length=10, verbose_name='Код ОКПО')),
                ('register_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата регистрации юр.лица')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заполнения')),
                ('owner_full_name', models.CharField(max_length=300, verbose_name='ФИО руководителя')),
                ('date_of_signing', models.DateTimeField(blank=True, null=True, verbose_name='Дата подписания заявки')),
                ('review_period', models.DateTimeField(blank=True, null=True, verbose_name='Срок рассмотрения')),
                ('finish_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата фактического рассмотрения')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Создано'), (1, 'Принято на рассмотрение'), (2, 'Одобрено'), (3, 'отказано')], null=True, verbose_name='Статус заявки')),
                ('application_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Подача'), (1, 'Переоформление'), (2, 'Отказ'), (3, 'Продление')], null=True, verbose_name='Тип заявки')),
                ('is_archived', models.BooleanField(default=False)),
                ('signature', models.CharField(blank=True, max_length=500, null=True, verbose_name='Подпись')),
                ('sedo_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Код с СЭД')),
                ('cause', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('doc', models.FileField(blank=True, null=True, upload_to='applications/docs/')),
                ('approved_by_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications_as_director', to=settings.AUTH_USER_MODEL, verbose_name='Одобрено директором')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('application'), models.Model),
        ),
    ]
