# Generated by Django 5.2.4 on 2025-11-17 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        ('license_template', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='license_type',
            field=models.ManyToManyField(blank=True, related_name='applications', to='license_template.licensetype', verbose_name='Тип лицензии'),
        ),
        migrations.AddField(
            model_name='application',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='organization.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='applicationemployee',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='application.application', unique=True, verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='applicationemployee',
            name='employees',
            field=models.ManyToManyField(related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='Назначенные сотрудники'),
        ),
        migrations.AddField(
            model_name='approvedrejected',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_rejection', to='application.application', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='approvedrejected',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approveds', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to='application.application', verbose_name='Заявка'),
        ),
    ]
