# Generated by Django 5.2.4 on 2026-01-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(max_length=15, unique=True, verbose_name='ИНН организации'),
        ),
    ]
