# Generated by Django 5.2.4 on 2025-11-17 06:05

import django.db.models.deletion
import django_prometheus.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number_start', models.PositiveIntegerField(default=1, verbose_name='Начальный номер лицензии (без нулей)')),
            ],
            options={
                'verbose_name': 'Значения по умолчанию для лицензии',
                'verbose_name_plural': 'Значения по умолчанию для лицензий',
            },
        ),
        migrations.CreateModel(
            name='LicenseTemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=150, verbose_name='Название поля')),
                ('field_type', models.PositiveSmallIntegerField(choices=[(0, 'Текст'), (1, 'Число'), (2, 'Булевое'), (3, 'Документ'), (4, 'Объем')], verbose_name='Тип данных поля')),
            ],
            options={
                'verbose_name': 'Поле шаблона лицензии',
                'verbose_name_plural': 'Поля шаблонов лицензий',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('license-template-field'), models.Model),
        ),
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('detailed_description', tinymce.models.HTMLField(blank=True, verbose_name='Описание в справочнике')),
                ('detailed_description_ru', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание в справочнике')),
                ('detailed_description_ky', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание в справочнике')),
                ('expiration_date', models.DateField(blank=True, help_text='Если лицензия бессрочная — оставьте поле пустым', null=True, verbose_name='Срок действия лицензии')),
                ('license_type', models.IntegerField(choices=[(0, 'Отчуждаемая'), (1, 'Неотчуждаемая')], verbose_name='Лицензия является')),
                ('license_terms', models.TextField(verbose_name='Лицензионные условия')),
                ('license_terms_ru', models.TextField(null=True, verbose_name='Лицензионные условия')),
                ('license_terms_ky', models.TextField(null=True, verbose_name='Лицензионные условия')),
            ],
            options={
                'verbose_name': 'Тип лицензии',
                'verbose_name_plural': 'Типы лицензий',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('license-type'), models.Model),
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Регистрационный номер по реестру лицензий')),
                ('issued_date', models.DateField(verbose_name='Дата выдачи')),
                ('issued_by', models.CharField(max_length=255, verbose_name='Выдана')),
                ('licensee_address', models.TextField(verbose_name='Адрес лицензиата')),
                ('state_registration_certificate', models.CharField(max_length=255, verbose_name='Свидетельство о государственной регистрации')),
                ('state_registration_issued_by', models.CharField(max_length=255, verbose_name='Кем выдана государственная регистрация')),
                ('inn', models.CharField(max_length=14, verbose_name='Идентификационный код (ИНН)')),
                ('expiration_date', models.DateField(blank=True, help_text='Если лицензия бессрочная — оставьте поле пустым', null=True, verbose_name='Срок действия лицензии')),
                ('expired', models.BooleanField(default=False, max_length=10, verbose_name='Анулировано')),
                ('registrable_type', models.IntegerField(choices=[(0, 'Отчуждаемая'), (1, 'Неотчуждаемая')], verbose_name='Лицензия является')),
                ('status', models.BooleanField(default=True, max_length=10, verbose_name='Статус')),
                ('volume', models.CharField(blank=True, max_length=200, null=True, verbose_name='Объем')),
                ('volume_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Объем')),
                ('volume_ky', models.CharField(blank=True, max_length=200, null=True, verbose_name='Объем')),
                ('license_terms', models.TextField(blank=True, null=True, verbose_name='Лицензионные условия')),
                ('license_terms_ru', models.TextField(blank=True, null=True, verbose_name='Лицензионные условия')),
                ('license_terms_ky', models.TextField(blank=True, null=True, verbose_name='Лицензионные условия')),
                ('document', models.FileField(blank=True, null=True, upload_to='licenses/docs/')),
                ('direct_aproved', models.BooleanField(default=False)),
                ('suspension', models.BooleanField(default=False)),
                ('suspension_date', models.DateField(blank=True, null=True)),
                ('signature', models.CharField(blank=True, max_length=6000, null=True, verbose_name='Подпись')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='application.application', verbose_name='Заявка')),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='license_template.licensetype', verbose_name='Тип лицензии')),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лицензии',
            },
        ),
        migrations.CreateModel(
            name='LicenseAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_actions', to='application.application', verbose_name='Заявка')),
                ('licenses', models.ManyToManyField(related_name='actions', to='license_template.license', verbose_name='Лицензии')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseTemplateFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Значение')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='application.application', verbose_name='Заявка')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='license_template.licensetemplatefield', verbose_name='Поле')),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='license_template.licensetype', verbose_name='Тип лицензии')),
            ],
            options={
                'verbose_name': 'Значение поля шаблона лицензии',
                'verbose_name_plural': 'Значения полей шаблонов лицензий',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('license-template-field-value'), models.Model),
        ),
        migrations.CreateModel(
            name='LicenseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название шаблона лицензии')),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='license_template.licensetype', verbose_name='Тип лицензии')),
            ],
            options={
                'verbose_name': 'Шаблон лицензии',
                'verbose_name_plural': 'Шаблоны лицензий',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('license-template'), models.Model),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Деятельность')),
                ('license_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='license_template.licensetype')),
            ],
            options={
                'verbose_name': 'Деятельностей',
                'verbose_name_plural': 'Деятельности',
            },
        ),
        migrations.CreateModel(
            name='LicenseTemplateFieldOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательное поле')),
                ('min_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальное значение')),
                ('max_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальное значение')),
                ('is_static', models.BooleanField(default=False, verbose_name='Статичное поле')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание для поля')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_order', to='license_template.licensetemplatefield', verbose_name='Поля')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_order', to='license_template.licensetemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Порядок полей шаблона лицензии',
                'verbose_name_plural': 'Порядок полей шаблона лицензии',
                'ordering': ['order'],
                'unique_together': {('template', 'field')},
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('license-template-field-order'), models.Model),
        ),
    ]
