# Generated by Django 5.2.7 on 2025-12-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Импорт Excel',
                'verbose_name_plural': 'Импорт Excel',
                'managed': False,
            },
        ),
    ]
