# Generated by Django 5.2.4 on 2026-02-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_template', '0002_excelimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensetype',
            name='license_group',
            field=models.IntegerField(blank=True, choices=[(0, 'Тепловая энергия'), (1, 'Электрическая энергия'), (2, 'Нефть'), (3, 'Газ')], null=True, verbose_name='Группа лицензии'),
        ),
    ]
